using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Mixins;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.LogicalTree;
using Avalonia.VisualTree;

namespace FluentAvalonia.UI.Controls
{
	public class ListViewItem : ListBoxItem
	{
		public ListViewItem()
		{

		}

		static ListViewItem()
		{
			FocusableProperty.OverrideDefaultValue<ListViewItem>(true);
		}		

		/// <summary>
		/// Flag that indicates whether the ListViewItem as generated by the ListView and is eligible for the
		/// recycle pool. If this flag is false, it was generated by user (via ChoosingItemContainer event) and
		/// user is responsible for recycling their own containers
		/// </summary>
		internal bool WasGeneratedByListView { get; set; }

		protected override void OnGotFocus(GotFocusEventArgs e)
		{
			base.OnGotFocus(e);

			var lv = this.FindAncestorOfType<ListViewBase>();
			if (lv != null)
			{
				lv.UpdateSelectionFromItemFocus(this);
			}
		}
	}
}
